---
title: "A simple rank 1 example"
author: "Matthew Stephens"
date: "9/13/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# A simple rank 1 simulation

First we will simulate some rank 1 data:

```{r}
  library("flashr")
  set.seed(1)
  n=100
  p=1000
  ll = rnorm(n)
  ff = rnorm(p)
  LF = outer(ll,ff)
  Y = LF + rnorm(n*p)
```

Now add some missing data at 50 percent of entries

```{r}
  Y.miss = Y
  for(i in 1:n){ # set half of Y to be missign at random
    Y.miss[i,sample(1:p,p/2)]=NA
  }
```

Run flash on the full data
```{r}
  data = flash_set_data(Y)
  f= flash_r1(data,verbose=TRUE)
  plot(LF,flash_get_lf(f),main="True LF vs fitted value (full data)",xlab="true LF",ylab="fitted LF")
  abline(a=0,b=1,col="red")
```

And on missing data
```{r}  
  data.miss = flash_set_data(Y.miss)
  f.miss = flash_r1(data.miss,verbose=TRUE)
  plot(LF,flash_get_lf(f.miss),main="True LF vs fitted values (missing data)",xlab="true LF",ylab="fitted LF")
  abline(a=0,b=1,col="red")
```

And compute overall RMSE of estimated low-rank structure.
```{r}  
  sqrt(mean((LF-flash_get_lf(f))^2))
  sqrt(mean((LF-flash_get_lf(f.miss))^2))
```

And compare with original flashr:
```{r}
  f.orig = flashr::greedy(Y,1)
  f.orig.na = flashr::greedy(Y.miss,1)
  
  plot(f.orig$f,f$EF,main="comparison of flashr and flashr factors",xlab="flashr",ylab="flashr")
   plot(f.orig$l,f$EL,main="comparison of flashr and flashr loadings",xlab="flashr",ylab="flashr")
  
  sqrt(mean((LF-outer(f.orig$l,f.orig$f))^2))
  sqrt(mean((LF-outer(f.orig.na$l,f.orig.na$f))^2))

```

And try setting the ash parameters slightly differently:
```{r}
  f= flash_r1(data,ash_param = list(method="fdr"),verbose=TRUE)
  plot(LF,flash_get_lf(f),main="True LF vs fitted value (full data)",xlab="true LF",ylab="fitted LF")
  abline(a=0,b=1,col="red")
  sqrt(mean((LF-flash_get_lf(f))^2))
```

And try setting the var_type slightly differently:
```{r}
  f= flash_r1(data,var_type = "constant",verbose=TRUE)
  plot(LF,flash_get_lf(f),main="True LF vs fitted value (full data)",xlab="true LF",ylab="fitted LF")
  abline(a=0,b=1,col="red")
  sqrt(mean((LF-flash_get_lf(f))^2))
  
  f.miss = flash_r1(data.miss,var_type = "constant",verbose=TRUE)
  plot(LF,flash_get_lf(f.miss),main="True LF vs fitted values (missing data)",xlab="true LF",ylab="fitted LF")
  abline(a=0,b=1,col="red")
  sqrt(mean((LF-flash_get_lf(f.miss))^2))
```

